import { Project } from '../types';

export const INITIAL_EMPTY_PROJECT: Project = {
  id: 'proj_new_workspace',
  title: 'UNTITLED CINEMA PROJECT',
  type: 'movie',
  director: 'Cinematic Creator',
  year: new Date().getFullYear(),
  genre: ['Cinema'],
  synopsis: 'No movie loaded. Ingest a video file to run multimodal cinema intelligence with Gemini.',
  duration: '00:00:00',
  durationSec: 0,
  resolution: '1080p',
  fps: 24,
  posterUrl: '',
  videoSourceUrl: '',
  status: 'idle',
  analysisStatus: 'NOT ANALYZED',
  storyPotentialScore: 0,
  analysis: {
    overallScore: 0,
    charactersCount: 0,
    keyEventsCount: 0,
    twistsCount: 0,
    suspensePointsCount: 0,
    emotionalMomentsCount: 0,
    narrationSyncScore: 0,
    sceneMatchingScore: 0,
    audioScore: 0,
    subtitlesScore: 0,
    pacingScore: 0,
    continuityScore: 0
  },
  scenes: [],
  characters: [],
  events: [],
  twists: [],
  suspensePoints: [],
  emotionalMoments: [],
  actionSequences: [],
  locations: [],
  objects: [],
  scannedFrames: [],
  knowledgeGraphNodes: [],
  knowledgeGraphEdges: [],
  storyGraph: [],
  script: {
    id: 'script_init',
    title: 'Explainer Script',
    projectId: 'proj_init',
    language: 'English',
    wordsCount: 0,
    targetDuration: '0 min',
    targetDurationSec: 0,
    estimatedNarrationDuration: '00:00',
    estimatedNarrationSec: 0,
    segments: []
  },
  timeline: {
    id: 'tl_init',
    projectId: 'proj_init',
    name: 'Master Cut',
    totalDuration: 0,
    durationSec: 0,
    currentTime: 0,
    fps: 24,
    playheadSec: 0,
    isPlaying: false,
    zoomLevel: 1,
    tracks: [
      { id: 'v1', name: 'V1 // Source Video', type: 'video', isMuted: false, isLocked: false, isSolo: false, color: '#00f0ff', clips: [] },
      { id: 'v2', name: 'V2 // B-Roll & Visuals', type: 'video', isMuted: false, isLocked: false, isSolo: false, color: '#3b82f6', clips: [] },
      { id: 't1', name: 'T1 // Explainer Subtitles', type: 'subtitles', isMuted: false, isLocked: false, isSolo: false, color: '#f59e0b', clips: [] },
      { id: 'a1', name: 'A1 // Master Voiceover', type: 'narration', isMuted: false, isLocked: false, isSolo: false, color: '#10b981', clips: [] },
      { id: 'a2', name: 'A2 // Soundtrack / Score', type: 'music', isMuted: false, isLocked: false, isSolo: false, color: '#8b5cf6', clips: [] },
      { id: 'a3', name: 'A3 // Cinematic SFX', type: 'sfx', isMuted: false, isLocked: false, isSolo: false, color: '#ec4899', clips: [] }
    ]
  },
  subtitles: [],
  shorts: [],
  thumbnails: [],
  seo: {
    titleVariants: [],
    descriptions: [],
    tags: [],
    chapters: [],
    viralHooks: [],
    overallSeoScore: 0
  },
  lastEdited: new Date().toISOString(),
  createdAt: new Date().toISOString()
};

export const DEMO_PROJECTS: Project[] = [INITIAL_EMPTY_PROJECT];
