/**
 * THE DEVIL'S EYE - Voice Acting Mode Library
 * 60 Professional Acting, Emotion, and Delivery Profiles
 * Designed for Google Cloud TTS & Gemini Voice Acting System.
 * 
 * CORE VOICE RULE:
 * Changing mode modifies performance, emotional direction, pacing, pauses, and intensity,
 * but NEVER alters the Master Voice identity.
 */

import { VoiceActingMode } from '../types';

export const VOICE_ACTING_MODES: VoiceActingMode[] = [
  {
    id: 'natural',
    number: 1,
    name: 'NATURAL',
    category: 'Emotional & Human',
    description: 'Human conversational cadence, fluid cadence, unforced pauses, and neutral clarity.',
    defaultRate: 1.0,
    defaultPitch: 0.0,
    defaultIntensity: 50,
    defaultEmotion: 'Neutral',
    defaultEnergy: 50,
    defaultDramatic: 25,
    defaultSuspense: 15,
    pauseSentenceMs: 350,
    pauseParagraphMs: 650,
    emphasisLevel: 'subtle',
    actingDirections: 'Conversational delivery, authentic human pauses, gentle stress on key verbs, unhurried and sincere.',
    stylePrompt: 'Speak naturally like an engaging conversationalist sharing an interesting story with a friend.'
  },
  {
    id: 'cinematic',
    number: 2,
    name: 'CINEMATIC',
    category: 'Cinematic & Trailer',
    description: 'Controlled dramatic pauses, strong emphasis on key moments, wide dynamic range, and cinema cadence.',
    defaultRate: 0.96,
    defaultPitch: -1.2,
    defaultIntensity: 75,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 70,
    defaultDramatic: 85,
    defaultSuspense: 60,
    pauseSentenceMs: 500,
    pauseParagraphMs: 900,
    emphasisLevel: 'strong',
    actingDirections: 'Cinematic delivery, controlled dramatic pauses, strong emphasis on important words, wide emotional range, natural pitch variation, dramatic sentence endings.',
    stylePrompt: 'Speak like an iconic cinematic movie narrator with deliberate dramatic pauses and theatrical gravity.'
  },
  {
    id: 'drama',
    number: 3,
    name: 'DRAMA',
    category: 'Emotional & Human',
    description: 'Deep emotional performance, expressive pauses, character empathy, and nuanced dynamic delivery.',
    defaultRate: 0.94,
    defaultPitch: -0.5,
    defaultIntensity: 70,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 65,
    defaultDramatic: 80,
    defaultSuspense: 40,
    pauseSentenceMs: 450,
    pauseParagraphMs: 850,
    emphasisLevel: 'strong',
    actingDirections: 'Emotional performance, expressive pauses, stronger emotional emphasis, character-like delivery, natural intensity variation.',
    stylePrompt: 'Deliver with intense dramatic sincerity and emotional vulnerability, capturing tragic human conflict.'
  },
  {
    id: 'news_reader',
    number: 4,
    name: 'NEWS READER',
    category: 'Documentary & News',
    description: 'Authoritative, clear pronunciation, controlled pacing, minimal emotional exaggeration, high clarity.',
    defaultRate: 1.08,
    defaultPitch: 0.5,
    defaultIntensity: 50,
    defaultEmotion: 'Serious',
    defaultEnergy: 60,
    defaultDramatic: 15,
    defaultSuspense: 10,
    pauseSentenceMs: 280,
    pauseParagraphMs: 500,
    emphasisLevel: 'moderate',
    actingDirections: 'Authoritative, clear pronunciation, controlled pacing, professional delivery, minimal emotional exaggeration, strong clarity.',
    stylePrompt: 'Speak like a premier global broadcast news anchor with crisp articulation, unyielding clarity, and factual authority.'
  },
  {
    id: 'documentary',
    number: 5,
    name: 'DOCUMENTARY',
    category: 'Documentary & News',
    description: 'Informative, intelligent, calm, confident, natural pacing, subtle emotional undertone.',
    defaultRate: 0.98,
    defaultPitch: -0.8,
    defaultIntensity: 55,
    defaultEmotion: 'Confidence',
    defaultEnergy: 50,
    defaultDramatic: 45,
    defaultSuspense: 30,
    pauseSentenceMs: 400,
    pauseParagraphMs: 750,
    emphasisLevel: 'moderate',
    actingDirections: 'Informative, intelligent, calm, confident, natural pacing, subtle emotion, analytical contemplation.',
    stylePrompt: 'Deliver in the measured, intelligent cadence of a premium BBC or Netflix historical documentary narrator.'
  },
  {
    id: 'movie_trailer',
    number: 6,
    name: 'MOVIE TRAILER',
    category: 'Cinematic & Trailer',
    description: 'Powerful, deep dramatic delivery, strategic pauses, strong emphasis, high intensity, cinematic buildup.',
    defaultRate: 0.90,
    defaultPitch: -2.5,
    defaultIntensity: 90,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 85,
    defaultDramatic: 95,
    defaultSuspense: 80,
    pauseSentenceMs: 600,
    pauseParagraphMs: 1100,
    emphasisLevel: 'strong',
    actingDirections: 'Powerful, deep dramatic delivery, strategic pauses, strong emphasis, high intensity, cinematic buildup, thunderous weight.',
    stylePrompt: 'Deliver like a blockbuster Hollywood theatrical trailer voiceover with deep low-end resonance and earth-shattering pauses.'
  },
  {
    id: 'storyteller',
    number: 7,
    name: 'STORYTELLER',
    category: 'Character & Narrative',
    description: 'Captivating oral narrative, rhythmic cadence, intimacy, vocal color, and narrative suspense.',
    defaultRate: 0.98,
    defaultPitch: 0.0,
    defaultIntensity: 65,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 60,
    defaultDramatic: 65,
    defaultSuspense: 45,
    pauseSentenceMs: 420,
    pauseParagraphMs: 800,
    emphasisLevel: 'moderate',
    actingDirections: 'Warm narrative magnetism, inviting tone, dramatic micro-pauses before reveals, fluid inflection.',
    stylePrompt: 'Speak like a master fireside oral storyteller drawing listeners into an irresistible mythic tale.'
  },
  {
    id: 'mystery',
    number: 8,
    name: 'MYSTERY',
    category: 'Atmospheric & Thriller',
    description: 'Controlled, quiet intensity, slower pacing, strategic pauses, subtle suspense, emphasis on clues.',
    defaultRate: 0.92,
    defaultPitch: -1.0,
    defaultIntensity: 65,
    defaultEmotion: 'Mysterious',
    defaultEnergy: 45,
    defaultDramatic: 70,
    defaultSuspense: 85,
    pauseSentenceMs: 550,
    pauseParagraphMs: 950,
    emphasisLevel: 'moderate',
    actingDirections: 'Controlled, quiet intensity, slower pacing, strategic pauses, subtle suspense, emphasis on clues, lingering whispers.',
    stylePrompt: 'Speak in a hushed, enigmatic mystery tone where every word drops a cryptic forensic clue.'
  },
  {
    id: 'suspense',
    number: 9,
    name: 'SUSPENSE',
    category: 'Atmospheric & Thriller',
    description: 'Gradually increasing tension, variable pacing, meaningful pauses, controlled intensity, climax near reveals.',
    defaultRate: 0.95,
    defaultPitch: -0.6,
    defaultIntensity: 75,
    defaultEmotion: 'Suspense',
    defaultEnergy: 70,
    defaultDramatic: 80,
    defaultSuspense: 92,
    pauseSentenceMs: 480,
    pauseParagraphMs: 900,
    emphasisLevel: 'strong',
    actingDirections: 'Gradually increasing tension, variable pacing, meaningful pauses, controlled intensity, stronger delivery near reveal points.',
    stylePrompt: 'Deliver with mounting psychological suspense, steady heartbeat pacing, and tension that tightens with every breath.'
  },
  {
    id: 'horror',
    number: 10,
    name: 'HORROR',
    category: 'Atmospheric & Thriller',
    description: 'Dark, restrained, unsettling, slow dramatic delivery, long pauses, controlled supernatural intensity.',
    defaultRate: 0.88,
    defaultPitch: -1.8,
    defaultIntensity: 80,
    defaultEmotion: 'Fear',
    defaultEnergy: 55,
    defaultDramatic: 85,
    defaultSuspense: 95,
    pauseSentenceMs: 650,
    pauseParagraphMs: 1200,
    emphasisLevel: 'strong',
    actingDirections: 'Dark, restrained, unsettling, slow dramatic delivery, long pauses, controlled intensity, eerie undertones.',
    stylePrompt: 'Speak in a chilling, restrained psychological horror register that evokes unnamable dread in the dark.'
  },
  {
    id: 'psychological',
    number: 11,
    name: 'PSYCHOLOGICAL',
    category: 'Atmospheric & Thriller',
    description: 'Subtle paranoia, inward contemplation, shifting cognitive reality, quiet tension, and analytical depth.',
    defaultRate: 0.93,
    defaultPitch: -0.4,
    defaultIntensity: 65,
    defaultEmotion: 'Mysterious',
    defaultEnergy: 50,
    defaultDramatic: 75,
    defaultSuspense: 80,
    pauseSentenceMs: 460,
    pauseParagraphMs: 820,
    emphasisLevel: 'moderate',
    actingDirections: 'Introspective, calculating, unhurried, questioning reality, deliberate cerebral pauses.',
    stylePrompt: 'Speak with penetrating psychological focus, dissecting motive, deceit, and mental labyrinths.'
  },
  {
    id: 'dark',
    number: 12,
    name: 'DARK',
    category: 'Atmospheric & Thriller',
    description: 'Heavy low-frequency presence, grim outlook, unflinching gravity, and bleak atmospheric weight.',
    defaultRate: 0.90,
    defaultPitch: -2.0,
    defaultIntensity: 78,
    defaultEmotion: 'Serious',
    defaultEnergy: 60,
    defaultDramatic: 80,
    defaultSuspense: 75,
    pauseSentenceMs: 520,
    pauseParagraphMs: 980,
    emphasisLevel: 'strong',
    actingDirections: 'Low resonance, fatalistic composure, somber emphasis, dark shadows in voice tone.',
    stylePrompt: 'Deliver with heavy noir darkness and unflinching moral realism.'
  },
  {
    id: 'emotional',
    number: 13,
    name: 'EMOTIONAL',
    category: 'Emotional & Human',
    description: 'Warm, expressive, slower delivery, emotional pauses, softer intensity, natural variation.',
    defaultRate: 0.92,
    defaultPitch: 0.2,
    defaultIntensity: 70,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 55,
    defaultDramatic: 85,
    defaultSuspense: 35,
    pauseSentenceMs: 480,
    pauseParagraphMs: 880,
    emphasisLevel: 'moderate',
    actingDirections: 'Warm, expressive, slower delivery, emotional pauses, softer intensity, natural human variation, heartfelt resonance.',
    stylePrompt: 'Speak with heartfelt emotional warmth and tender empathy, conveying deep sentimental bonds.'
  },
  {
    id: 'sad',
    number: 14,
    name: 'SAD',
    category: 'Emotional & Human',
    description: 'Slower, restrained, softer delivery, longer pauses, emotional weight, lingering sorrow.',
    defaultRate: 0.86,
    defaultPitch: -1.0,
    defaultIntensity: 65,
    defaultEmotion: 'Sad',
    defaultEnergy: 35,
    defaultDramatic: 75,
    defaultSuspense: 30,
    pauseSentenceMs: 600,
    pauseParagraphMs: 1100,
    emphasisLevel: 'subtle',
    actingDirections: 'Slower, restrained, softer delivery, longer pauses, emotional weight, falling terminal inflections.',
    stylePrompt: 'Deliver with profound quiet sorrow, soft sorrowful pacing, and lingering melancholy pauses.'
  },
  {
    id: 'happy',
    number: 15,
    name: 'HAPPY',
    category: 'Emotional & Human',
    description: 'Bright uplift, smiling resonance, brisk rhythmic vitality, and positive emotional radiation.',
    defaultRate: 1.06,
    defaultPitch: 1.5,
    defaultIntensity: 60,
    defaultEmotion: 'Happy',
    defaultEnergy: 75,
    defaultDramatic: 30,
    defaultSuspense: 10,
    pauseSentenceMs: 300,
    pauseParagraphMs: 550,
    emphasisLevel: 'moderate',
    actingDirections: 'Bright timbre, smiling vocal acoustic, energetic lift on punctuation, contagious enthusiasm.',
    stylePrompt: 'Speak with radiant joy, vibrant optimism, and uplifting conversational cheer.'
  },
  {
    id: 'romantic',
    number: 16,
    name: 'ROMANTIC',
    category: 'Emotional & Human',
    description: 'Intimate, warm, gentle vocal caress, soft breath dynamics, and affectionate lyricism.',
    defaultRate: 0.91,
    defaultPitch: -0.5,
    defaultIntensity: 55,
    defaultEmotion: 'Romantic',
    defaultEnergy: 40,
    defaultDramatic: 60,
    defaultSuspense: 25,
    pauseSentenceMs: 500,
    pauseParagraphMs: 900,
    emphasisLevel: 'subtle',
    actingDirections: 'Soft, intimate, velvety timbre, unhurried cadence, gentle melodic rises.',
    stylePrompt: 'Deliver with velvety intimacy, tenderness, and romantic affection.'
  },
  {
    id: 'calm',
    number: 17,
    name: 'CALM',
    category: 'Emotional & Human',
    description: 'Tranquil, even breathing, soothing presence, zero aggression, and peaceful reassurance.',
    defaultRate: 0.94,
    defaultPitch: -0.2,
    defaultIntensity: 40,
    defaultEmotion: 'Confidence',
    defaultEnergy: 35,
    defaultDramatic: 20,
    defaultSuspense: 10,
    pauseSentenceMs: 450,
    pauseParagraphMs: 800,
    emphasisLevel: 'none',
    actingDirections: 'Composed, meditative cadence, gentle rounded vowels, serene breathing.',
    stylePrompt: 'Speak in a peaceful, grounding, and steady manner that brings utter calmness.'
  },
  {
    id: 'serious',
    number: 18,
    name: 'SERIOUS',
    category: 'Documentary & News',
    description: 'Grave, weighty, non-indulgent, direct eye-contact vocal posture, and sober conviction.',
    defaultRate: 0.97,
    defaultPitch: -0.8,
    defaultIntensity: 65,
    defaultEmotion: 'Serious',
    defaultEnergy: 55,
    defaultDramatic: 50,
    defaultSuspense: 40,
    pauseSentenceMs: 380,
    pauseParagraphMs: 700,
    emphasisLevel: 'moderate',
    actingDirections: 'Firm articulation, sober weight, unwavering pitch center, direct and matter-of-fact.',
    stylePrompt: 'Deliver with serious professional gravity, unyielding conviction, and sober clarity.'
  },
  {
    id: 'angry',
    number: 19,
    name: 'ANGRY',
    category: 'Fast & High-Energy',
    description: 'Strong intensity, firm delivery, sharper emphasis, faster pacing, controlled aggression without distortion.',
    defaultRate: 1.10,
    defaultPitch: 0.8,
    defaultIntensity: 85,
    defaultEmotion: 'Angry',
    defaultEnergy: 90,
    defaultDramatic: 80,
    defaultSuspense: 50,
    pauseSentenceMs: 250,
    pauseParagraphMs: 500,
    emphasisLevel: 'sharp',
    actingDirections: 'Strong intensity, firm delivery, sharper emphasis, faster pacing where appropriate, controlled aggression, articulate fury, DO NOT become unintelligible.',
    stylePrompt: 'Deliver with fierce, controlled fury, biting consonant attacks, and intense vocal punch.'
  },
  {
    id: 'action',
    number: 20,
    name: 'ACTION',
    category: 'Fast & High-Energy',
    description: 'Energetic, fast-paced, high intensity, short pauses, strong emphasis, exciting delivery.',
    defaultRate: 1.15,
    defaultPitch: 0.5,
    defaultIntensity: 85,
    defaultEmotion: 'Excitement',
    defaultEnergy: 92,
    defaultDramatic: 75,
    defaultSuspense: 70,
    pauseSentenceMs: 220,
    pauseParagraphMs: 450,
    emphasisLevel: 'strong',
    actingDirections: 'Energetic, fast-paced, high intensity, short pauses, strong emphasis, exciting delivery, urgent momentum.',
    stylePrompt: 'Deliver with adrenaline-fueled kinetic drive, rapid punchy rhythm, and thrilling blockbuster action energy.'
  },
  {
    id: 'intense',
    number: 21,
    name: 'INTENSE',
    category: 'Fast & High-Energy',
    description: 'High-stakes urgency, laser-sharp focus, taut breathing, and vibrating vocal energy.',
    defaultRate: 1.08,
    defaultPitch: 0.3,
    defaultIntensity: 88,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 85,
    defaultDramatic: 88,
    defaultSuspense: 80,
    pauseSentenceMs: 280,
    pauseParagraphMs: 550,
    emphasisLevel: 'strong',
    actingDirections: 'Tight vocal cords, breathless drive, sharp crisp syllables, uncompromising forward momentum.',
    stylePrompt: 'Speak with blistering intensity and high-stakes psychological tension.'
  },
  {
    id: 'epic',
    number: 22,
    name: 'EPIC',
    category: 'Cinematic & Trailer',
    description: 'Monumental scale, mythological weight, expansive reverberant vowels, and heroic glory.',
    defaultRate: 0.92,
    defaultPitch: -1.8,
    defaultIntensity: 90,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 88,
    defaultDramatic: 95,
    defaultSuspense: 60,
    pauseSentenceMs: 550,
    pauseParagraphMs: 1000,
    emphasisLevel: 'strong',
    actingDirections: 'Expansive vocal projection, panoramic scale, proud regal cadence, legendary historical gravitas.',
    stylePrompt: 'Speak like an ancient bard recounting a clash of civilizations or the birth of an epic legend.'
  },
  {
    id: 'shocked',
    number: 23,
    name: 'SHOCKED',
    category: 'Climax & Twist',
    description: 'Gasping cadence, sudden cognitive jolt, fractured pacing, and incredulous disbelief.',
    defaultRate: 1.05,
    defaultPitch: 1.8,
    defaultIntensity: 85,
    defaultEmotion: 'Surprise',
    defaultEnergy: 80,
    defaultDramatic: 90,
    defaultSuspense: 85,
    pauseSentenceMs: 350,
    pauseParagraphMs: 650,
    emphasisLevel: 'sharp',
    actingDirections: 'Stunned breath intake, sudden deceleration then rapid burst, disbelieving pitch inflections.',
    stylePrompt: 'Speak in a stunned, breathless voice reeling from an impossible visual realization.'
  },
  {
    id: 'surprised',
    number: 24,
    name: 'SURPRISED',
    category: 'Climax & Twist',
    description: 'Elevated pitch arc, sharp intake, sudden brightness, and genuine revelation.',
    defaultRate: 1.08,
    defaultPitch: 1.4,
    defaultIntensity: 70,
    defaultEmotion: 'Surprise',
    defaultEnergy: 75,
    defaultDramatic: 65,
    defaultSuspense: 60,
    pauseSentenceMs: 300,
    pauseParagraphMs: 600,
    emphasisLevel: 'moderate',
    actingDirections: 'Rising pitch on key revelations, sudden animated sparkle, spontaneous reaction.',
    stylePrompt: 'Deliver with authentic astonishment and wide-eyed verbal wonder.'
  },
  {
    id: 'fearful',
    number: 25,
    name: 'FEARFUL',
    category: 'Atmospheric & Thriller',
    description: 'Trembling micro-tones, restrained volume, shallow breath, and imminent threat anticipation.',
    defaultRate: 0.95,
    defaultPitch: 0.6,
    defaultIntensity: 80,
    defaultEmotion: 'Fear',
    defaultEnergy: 65,
    defaultDramatic: 85,
    defaultSuspense: 95,
    pauseSentenceMs: 400,
    pauseParagraphMs: 750,
    emphasisLevel: 'sharp',
    actingDirections: 'Guarded volume, tremor in voice tail, rapid defensive scanning cadence, heightened vulnerability.',
    stylePrompt: 'Speak with palpable dread as if hiding from an unseen stalker mere feet away.'
  },
  {
    id: 'whisper',
    number: 26,
    name: 'WHISPER / LOW INTENSITY',
    category: 'Atmospheric & Thriller',
    description: 'Sub-audible breathiness, close-mic intimacy, conspiracy sharing, and confidential secrets.',
    defaultRate: 0.88,
    defaultPitch: -0.5,
    defaultIntensity: 35,
    defaultEmotion: 'Mysterious',
    defaultEnergy: 30,
    defaultDramatic: 70,
    defaultSuspense: 85,
    pauseSentenceMs: 500,
    pauseParagraphMs: 950,
    emphasisLevel: 'subtle',
    actingDirections: 'Near-whisper sibilance, ultra-intimate proximity, hushed secretive pacing, goosebump generator.',
    stylePrompt: 'Speak in a hushed ASMR-like close-mic whisper revealing classified forensic secrets.'
  },
  {
    id: 'confident',
    number: 27,
    name: 'CONFIDENT',
    category: 'Documentary & News',
    description: 'Unflinching certainty, grounded chest resonance, steady pace, and effortless dominance.',
    defaultRate: 1.02,
    defaultPitch: -0.4,
    defaultIntensity: 65,
    defaultEmotion: 'Confidence',
    defaultEnergy: 70,
    defaultDramatic: 40,
    defaultSuspense: 20,
    pauseSentenceMs: 320,
    pauseParagraphMs: 600,
    emphasisLevel: 'moderate',
    actingDirections: 'Firm bottom-end, relaxed diaphragm, zero hesitation, clean decisive terminal punctuation.',
    stylePrompt: 'Speak with masterly confidence and effortless intellectual authority.'
  },
  {
    id: 'motivational',
    number: 28,
    name: 'MOTIVATIONAL',
    category: 'Character & Narrative',
    description: 'Igniting inner drive, progressive volume swell, resolute cadence, and rallying spirit.',
    defaultRate: 1.02,
    defaultPitch: 0.4,
    defaultIntensity: 80,
    defaultEmotion: 'Confidence',
    defaultEnergy: 85,
    defaultDramatic: 75,
    defaultSuspense: 30,
    pauseSentenceMs: 360,
    pauseParagraphMs: 700,
    emphasisLevel: 'strong',
    actingDirections: 'Steadily building crescendo, impassioned conviction, inspiring uplift on calls to action.',
    stylePrompt: 'Deliver like a championship locker-room speech turning doubt into unbreakable resolve.'
  },
  {
    id: 'inspirational',
    number: 29,
    name: 'INSPIRATIONAL',
    category: 'Character & Narrative',
    description: 'Luminosity, spiritual elevation, touching universal truths, and hopeful cadence.',
    defaultRate: 0.96,
    defaultPitch: 0.2,
    defaultIntensity: 70,
    defaultEmotion: 'Happy',
    defaultEnergy: 70,
    defaultDramatic: 70,
    defaultSuspense: 25,
    pauseSentenceMs: 440,
    pauseParagraphMs: 850,
    emphasisLevel: 'moderate',
    actingDirections: 'Warm golden resonance, poetic pacing, visionary projection, heartfelt elevation.',
    stylePrompt: 'Speak with poetic awe and emotional uplift, inspiring the audience to look beyond the stars.'
  },
  {
    id: 'funny',
    number: 30,
    name: 'FUNNY',
    category: 'Character & Narrative',
    description: 'Playful, light, expressive timing, comedic pauses, energetic variation, natural humor.',
    defaultRate: 1.08,
    defaultPitch: 1.0,
    defaultIntensity: 60,
    defaultEmotion: 'Humorous',
    defaultEnergy: 75,
    defaultDramatic: 35,
    defaultSuspense: 20,
    pauseSentenceMs: 320,
    pauseParagraphMs: 650,
    emphasisLevel: 'moderate',
    actingDirections: 'Playful, light, expressive timing, comedic pauses, energetic variation, natural humor, wink in the tone.',
    stylePrompt: 'Deliver with witty banter, self-aware comedic timing, and vibrant amusement.'
  },
  {
    id: 'comedy',
    number: 31,
    name: 'COMEDY',
    category: 'Character & Narrative',
    description: 'Exaggerated beat drops, punchline setups, vocal elasticity, and cartoonish satire.',
    defaultRate: 1.12,
    defaultPitch: 1.2,
    defaultIntensity: 65,
    defaultEmotion: 'Humorous',
    defaultEnergy: 80,
    defaultDramatic: 40,
    defaultSuspense: 20,
    pauseSentenceMs: 340,
    pauseParagraphMs: 700,
    emphasisLevel: 'strong',
    actingDirections: 'Snappy rhythmic delivery, deliberate dramatic beat pause right before the punchline word, bounce.',
    stylePrompt: 'Deliver with stand-up comedy precision and buoyant satirical energy.'
  },
  {
    id: 'sarcastic',
    number: 32,
    name: 'SARCASTIC',
    category: 'Character & Narrative',
    description: 'Dry delivery, controlled irony, subtle emphasis, timing-focused pauses, cynical smirk.',
    defaultRate: 0.98,
    defaultPitch: -0.6,
    defaultIntensity: 65,
    defaultEmotion: 'Humorous',
    defaultEnergy: 55,
    defaultDramatic: 45,
    defaultSuspense: 30,
    pauseSentenceMs: 400,
    pauseParagraphMs: 750,
    emphasisLevel: 'sharp',
    actingDirections: 'Dry delivery, controlled irony, subtle emphasis, timing-focused pauses, deadpan flatline inflections.',
    stylePrompt: 'Speak in a razor-sharp deadpan tone dripping with sophisticated intellectual sarcasm.'
  },
  {
    id: 'casual',
    number: 33,
    name: 'CASUAL',
    category: 'Emotional & Human',
    description: 'Relaxed posture, everyday vernacular rhythm, zero stiffness, and easygoing flow.',
    defaultRate: 1.02,
    defaultPitch: 0.0,
    defaultIntensity: 45,
    defaultEmotion: 'Neutral',
    defaultEnergy: 50,
    defaultDramatic: 20,
    defaultSuspense: 15,
    pauseSentenceMs: 320,
    pauseParagraphMs: 600,
    emphasisLevel: 'subtle',
    actingDirections: 'Unbuttoned, effortless, slightly colloquial rhythm, approachable and grounded.',
    stylePrompt: 'Speak casually like an easygoing colleague chatting over coffee.'
  },
  {
    id: 'friendly',
    number: 34,
    name: 'FRIENDLY',
    category: 'Emotional & Human',
    description: 'Welcoming smile in voice, open acoustic resonance, hospitable rhythm, and cheerful clarity.',
    defaultRate: 1.04,
    defaultPitch: 0.8,
    defaultIntensity: 55,
    defaultEmotion: 'Happy',
    defaultEnergy: 65,
    defaultDramatic: 25,
    defaultSuspense: 10,
    pauseSentenceMs: 300,
    pauseParagraphMs: 580,
    emphasisLevel: 'moderate',
    actingDirections: 'Warm hospitable tone, upbeat greeting posture, gentle reassurance.',
    stylePrompt: 'Deliver in a warm, welcoming, and delightfully friendly tone.'
  },
  {
    id: 'energetic',
    number: 35,
    name: 'ENERGETIC',
    category: 'Fast & High-Energy',
    description: 'High-octane vocal spark, brisk syllable articulation, dynamic tempo, and infectious excitement.',
    defaultRate: 1.14,
    defaultPitch: 0.9,
    defaultIntensity: 80,
    defaultEmotion: 'Excitement',
    defaultEnergy: 90,
    defaultDramatic: 60,
    defaultSuspense: 40,
    pauseSentenceMs: 240,
    pauseParagraphMs: 460,
    emphasisLevel: 'strong',
    actingDirections: 'Rapid vocal engine, punchy phrase endings, enthusiastic forward thrust.',
    stylePrompt: 'Deliver with electric vibrancy, high tempo, and unstoppable kinetic passion.'
  },
  {
    id: 'fast_paced',
    number: 36,
    name: 'FAST PACED',
    category: 'Fast & High-Energy',
    description: 'Rapid-fire information delivery, seamless transitions, tight word gaps, YouTube retention velocity.',
    defaultRate: 1.22,
    defaultPitch: 0.2,
    defaultIntensity: 75,
    defaultEmotion: 'Confidence',
    defaultEnergy: 85,
    defaultDramatic: 50,
    defaultSuspense: 45,
    pauseSentenceMs: 180,
    pauseParagraphMs: 350,
    emphasisLevel: 'sharp',
    actingDirections: 'High words-per-minute articulation, zero sluggishness, razor-fast transitions, crisp consonants.',
    stylePrompt: 'Speak at ultra-high speed without losing a single drop of pristine syllabic clarity.'
  },
  {
    id: 'slow_dramatic',
    number: 37,
    name: 'SLOW DRAMATIC',
    category: 'Cinematic & Trailer',
    description: 'Deliberate ponderous cadence, monumental pauses, heavy emotional undertone, and cinematic weight.',
    defaultRate: 0.82,
    defaultPitch: -1.6,
    defaultIntensity: 80,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 50,
    defaultDramatic: 92,
    defaultSuspense: 75,
    pauseSentenceMs: 700,
    pauseParagraphMs: 1300,
    emphasisLevel: 'strong',
    actingDirections: 'Stately deceleration, heavy pregnant silences, immense psychological importance on every vowel.',
    stylePrompt: 'Speak with monumental slowness where every single word feels carved into granite.'
  },
  {
    id: 'climax',
    number: 38,
    name: 'CLIMAX',
    category: 'Climax & Twist',
    description: 'Maximum controlled intensity, strong emphasis, dramatic pauses, emotional variation, powerful ending.',
    defaultRate: 1.05,
    defaultPitch: -0.5,
    defaultIntensity: 95,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 95,
    defaultDramatic: 98,
    defaultSuspense: 88,
    pauseSentenceMs: 450,
    pauseParagraphMs: 850,
    emphasisLevel: 'strong',
    actingDirections: 'Maximum controlled intensity, strong emphasis, dramatic pauses, emotional variation, powerful ending, thunderous final peak.',
    stylePrompt: 'Deliver with peak theatrical climax intensity, electrifying drama, and monumental finality.'
  },
  {
    id: 'villain',
    number: 39,
    name: 'VILLAIN',
    category: 'Character & Narrative',
    description: 'Cold calculating malice, silky sinister undertones, mocking composure, and dangerous superiority.',
    defaultRate: 0.90,
    defaultPitch: -2.2,
    defaultIntensity: 85,
    defaultEmotion: 'Mysterious',
    defaultEnergy: 65,
    defaultDramatic: 88,
    defaultSuspense: 85,
    pauseSentenceMs: 500,
    pauseParagraphMs: 950,
    emphasisLevel: 'sharp',
    actingDirections: 'Silky smooth malice, icy patronizing pauses, low chest growl, calculating composure.',
    stylePrompt: 'Speak like an iconic cinematic mastermind holding all the cards with cold chilling elegance.'
  },
  {
    id: 'hero',
    number: 40,
    name: 'HERO',
    category: 'Character & Narrative',
    description: 'Noble steadfastness, moral spine, warm protective timbre, and unyielding courage.',
    defaultRate: 0.98,
    defaultPitch: -0.4,
    defaultIntensity: 75,
    defaultEmotion: 'Confidence',
    defaultEnergy: 75,
    defaultDramatic: 75,
    defaultSuspense: 50,
    pauseSentenceMs: 380,
    pauseParagraphMs: 720,
    emphasisLevel: 'strong',
    actingDirections: 'Resolute, morally upright, clear direct gaze, unyielding strength beneath gentle warmth.',
    stylePrompt: 'Deliver with the noble courage and steadfast resolve of an epic cinematic protagonist.'
  },
  {
    id: 'investigation',
    number: 41,
    name: 'INVESTIGATION',
    category: 'Atmospheric & Thriller',
    description: 'Forensic curiosity, piece-by-piece deduction, analytical interrogation, and clue synthesis.',
    defaultRate: 1.00,
    defaultPitch: -0.3,
    defaultIntensity: 65,
    defaultEmotion: 'Serious',
    defaultEnergy: 60,
    defaultDramatic: 60,
    defaultSuspense: 75,
    pauseSentenceMs: 360,
    pauseParagraphMs: 680,
    emphasisLevel: 'moderate',
    actingDirections: 'Inquisitive scrutiny, questioning inflection on clues, systematic deduction, methodical step-by-step logic.',
    stylePrompt: 'Deliver like a brilliant detective piecing together forensic evidence at a dark crime scene.'
  },
  {
    id: 'crime',
    number: 42,
    name: 'CRIME',
    category: 'Atmospheric & Thriller',
    description: 'Gritty street realism, hardboiled underworld flavor, smoky delivery, and cynical edge.',
    defaultRate: 0.94,
    defaultPitch: -1.4,
    defaultIntensity: 75,
    defaultEmotion: 'Serious',
    defaultEnergy: 65,
    defaultDramatic: 75,
    defaultSuspense: 80,
    pauseSentenceMs: 440,
    pauseParagraphMs: 820,
    emphasisLevel: 'strong',
    actingDirections: 'Hardboiled noir rasp, cynical urban swagger, streetwise pauses, unvarnished criminal reality.',
    stylePrompt: 'Speak like a hardboiled 1950s crime investigator narrating a dangerous mob underworld betrayal.'
  },
  {
    id: 'thriller',
    number: 43,
    name: 'THRILLER',
    category: 'Atmospheric & Thriller',
    description: 'Ticking clock paranoia, chase tempo, razor-wire tension, and relentless psychological danger.',
    defaultRate: 1.06,
    defaultPitch: 0.1,
    defaultIntensity: 85,
    defaultEmotion: 'Suspense',
    defaultEnergy: 85,
    defaultDramatic: 85,
    defaultSuspense: 95,
    pauseSentenceMs: 300,
    pauseParagraphMs: 600,
    emphasisLevel: 'sharp',
    actingDirections: 'Ticking clock urgency, breathless pursuit, sudden tempo shifts, electric danger.',
    stylePrompt: 'Deliver with high-octane political or psychological thriller tension where every second counts.'
  },
  {
    id: 'sci_fi',
    number: 44,
    name: 'SCI-FI',
    category: 'Cinematic & Trailer',
    description: 'Futuristic wonder, cosmic scale, technological precision, and deep existential contemplation.',
    defaultRate: 0.96,
    defaultPitch: -0.6,
    defaultIntensity: 70,
    defaultEmotion: 'Mysterious',
    defaultEnergy: 65,
    defaultDramatic: 80,
    defaultSuspense: 70,
    pauseSentenceMs: 460,
    pauseParagraphMs: 860,
    emphasisLevel: 'moderate',
    actingDirections: 'Awe-struck cosmic scope, sleek technological precision, philosophical expanse, otherworldly timbre.',
    stylePrompt: 'Speak like an interstellar expedition chronicler contemplating artificial intelligence and deep space anomalies.'
  },
  {
    id: 'action_trailer',
    number: 45,
    name: 'ACTION TRAILER',
    category: 'Cinematic & Trailer',
    description: 'Explosive punctuation, rapid rhythmic punch, bass-heavy drop, and maximum visceral impact.',
    defaultRate: 1.05,
    defaultPitch: -1.5,
    defaultIntensity: 92,
    defaultEmotion: 'Excitement',
    defaultEnergy: 95,
    defaultDramatic: 92,
    defaultSuspense: 75,
    pauseSentenceMs: 420,
    pauseParagraphMs: 800,
    emphasisLevel: 'sharp',
    actingDirections: 'Visceral impact, thunderous braam pauses, razor-sharp punchwords, stadium-sized energy.',
    stylePrompt: 'Deliver like a multi-million dollar summer blockbuster trailer voiceover.'
  },
  {
    id: 'breaking_news',
    number: 46,
    name: 'BREAKING NEWS',
    category: 'Documentary & News',
    description: 'Instant urgency, live event reporting, unscripted freshness, high alertness, and zero filler.',
    defaultRate: 1.12,
    defaultPitch: 0.6,
    defaultIntensity: 75,
    defaultEmotion: 'Serious',
    defaultEnergy: 80,
    defaultDramatic: 50,
    defaultSuspense: 60,
    pauseSentenceMs: 220,
    pauseParagraphMs: 420,
    emphasisLevel: 'strong',
    actingDirections: 'High adrenaline journalistic composure, immediate real-time reporting cadences, urgent alarms.',
    stylePrompt: 'Deliver as a breaking news special report interrupting regular broadcast programming.'
  },
  {
    id: 'sports_commentary',
    number: 47,
    name: 'SPORTS COMMENTARY',
    category: 'Fast & High-Energy',
    description: 'Play-by-play acceleration, stadium crescendo, emotional contagion, and breathless athletic climax.',
    defaultRate: 1.20,
    defaultPitch: 1.2,
    defaultIntensity: 85,
    defaultEmotion: 'Excitement',
    defaultEnergy: 98,
    defaultDramatic: 70,
    defaultSuspense: 70,
    pauseSentenceMs: 180,
    pauseParagraphMs: 380,
    emphasisLevel: 'sharp',
    actingDirections: 'Explosive color commentary, breathless rising pitches as the goal approaches, roaring crowd energy.',
    stylePrompt: 'Deliver with the electric fever pitch of a World Cup final 90th-minute winning goal call.'
  },
  {
    id: 'true_crime',
    number: 48,
    name: 'TRUE CRIME',
    category: 'Atmospheric & Thriller',
    description: 'Somber forensic autopsy, chilling understatement, respectful gravity, and disturbing investigative hooks.',
    defaultRate: 0.92,
    defaultPitch: -1.0,
    defaultIntensity: 72,
    defaultEmotion: 'Serious',
    defaultEnergy: 50,
    defaultDramatic: 75,
    defaultSuspense: 88,
    pauseSentenceMs: 500,
    pauseParagraphMs: 950,
    emphasisLevel: 'moderate',
    actingDirections: 'Quiet forensic chill, clinical dissection of horrific details, respectful somber pacing, chilling understatement.',
    stylePrompt: 'Speak like the master narrator of a viral True Crime podcast exposing an unsolved mystery.'
  },
  {
    id: 'factual',
    number: 49,
    name: 'FACTUAL',
    category: 'Documentary & News',
    description: 'Objective, scientific, clean data transmission, unclouded by subjective emotion, razor clarity.',
    defaultRate: 1.04,
    defaultPitch: 0.0,
    defaultIntensity: 45,
    defaultEmotion: 'Neutral',
    defaultEnergy: 50,
    defaultDramatic: 15,
    defaultSuspense: 10,
    pauseSentenceMs: 300,
    pauseParagraphMs: 550,
    emphasisLevel: 'moderate',
    actingDirections: 'Scientific neutrality, even syllabic distribution, crystal articulation, fact-based delivery.',
    stylePrompt: 'Speak with pure scientific precision, empirical clarity, and analytical objectivity.'
  },
  {
    id: 'professional',
    number: 50,
    name: 'PROFESSIONAL',
    category: 'Documentary & News',
    description: 'Corporate executive composure, boardroom authority, respectful elegance, and polished prestige.',
    defaultRate: 1.02,
    defaultPitch: -0.2,
    defaultIntensity: 55,
    defaultEmotion: 'Confidence',
    defaultEnergy: 58,
    defaultDramatic: 25,
    defaultSuspense: 15,
    pauseSentenceMs: 340,
    pauseParagraphMs: 620,
    emphasisLevel: 'moderate',
    actingDirections: 'Executive boardroom poise, dignified diction, measured confidence, polished cadence.',
    stylePrompt: 'Speak with executive corporate poise and pristine institutional authority.'
  },
  {
    id: 'serious_explainer',
    number: 51,
    name: 'SERIOUS EXPLAINER',
    category: 'Documentary & News',
    description: 'Deep-dive analytical education, thought-experiment unpacking, intellectual clarity, and engaging rigor.',
    defaultRate: 1.00,
    defaultPitch: -0.3,
    defaultIntensity: 60,
    defaultEmotion: 'Confidence',
    defaultEnergy: 60,
    defaultDramatic: 40,
    defaultSuspense: 35,
    pauseSentenceMs: 360,
    pauseParagraphMs: 680,
    emphasisLevel: 'moderate',
    actingDirections: 'Pedagogical brilliance, intuitive analogies, careful pacing on complex terms, intellectual grip.',
    stylePrompt: 'Speak like a master science or philosophy professor explaining a mind-bending paradigm shift.'
  },
  {
    id: 'youtube_explainer',
    number: 52,
    name: 'YOUTUBE EXPLAINER',
    category: 'Fast & High-Energy',
    description: 'Viral retention hooks, dynamic punchiness, audience-addressing charm, and punchy cliffhangers.',
    defaultRate: 1.12,
    defaultPitch: 0.5,
    defaultIntensity: 78,
    defaultEmotion: 'Excitement',
    defaultEnergy: 85,
    defaultDramatic: 60,
    defaultSuspense: 65,
    pauseSentenceMs: 240,
    pauseParagraphMs: 480,
    emphasisLevel: 'strong',
    actingDirections: 'High viewer-retention pacing, punchy vocal punches on visual beat changes, conversational swagger.',
    stylePrompt: 'Deliver with top-tier YouTube movie-explainer energy, gripping retention hooks, and rapid pacing.'
  },
  {
    id: 'reaction',
    number: 53,
    name: 'REACTION',
    category: 'Emotional & Human',
    description: 'Spontaneous commentary, visceral human response, vocal gasp, and unfiltered emotional sharing.',
    defaultRate: 1.08,
    defaultPitch: 1.1,
    defaultIntensity: 75,
    defaultEmotion: 'Surprise',
    defaultEnergy: 82,
    defaultDramatic: 70,
    defaultSuspense: 60,
    pauseSentenceMs: 280,
    pauseParagraphMs: 520,
    emphasisLevel: 'strong',
    actingDirections: 'Visceral human reaction, impromptu laughter or gasps, personal connection to the scene.',
    stylePrompt: 'Deliver with authentic spectator reaction, stunned realization, and live emotional engagement.'
  },
  {
    id: 'shock_reveal',
    number: 54,
    name: 'SHOCK / REVEAL',
    category: 'Climax & Twist',
    description: 'Controlled buildup, pause before reveal, strong emphasis on reveal, immediate pacing shift.',
    defaultRate: 0.94,
    defaultPitch: 0.4,
    defaultIntensity: 90,
    defaultEmotion: 'Surprise',
    defaultEnergy: 88,
    defaultDramatic: 95,
    defaultSuspense: 95,
    pauseSentenceMs: 600,
    pauseParagraphMs: 1100,
    emphasisLevel: 'strong',
    actingDirections: 'Controlled buildup, deliberate pause before reveal, strong emphasis on reveal, emotional reaction, immediate pacing shift after reveal.',
    stylePrompt: 'Build agonizing suspense, hold a total silence, and then deliver the shocking reveal with piercing dramatic emphasis.'
  },
  {
    id: 'twist_reveal',
    number: 55,
    name: 'TWIST REVEAL',
    category: 'Climax & Twist',
    description: 'Suspense buildup, deliberate pause, dramatic reveal, strong emphasis, controlled emotional reaction.',
    defaultRate: 0.90,
    defaultPitch: -1.2,
    defaultIntensity: 92,
    defaultEmotion: 'Mysterious',
    defaultEnergy: 85,
    defaultDramatic: 96,
    defaultSuspense: 98,
    pauseSentenceMs: 650,
    pauseParagraphMs: 1200,
    emphasisLevel: 'strong',
    actingDirections: 'Suspense buildup, deliberate pause, dramatic reveal, strong emphasis, controlled emotional reaction, reality inversion.',
    stylePrompt: 'Deliver the ultimate plot twist where everything the audience believed was a complete illusion.'
  },
  {
    id: 'suspense_buildup',
    number: 56,
    name: 'SUSPENSE BUILDUP',
    category: 'Atmospheric & Thriller',
    description: 'Progressive ratchet of anxiety, tightening tempo, stifled breathing, and nerve-shredding countdown.',
    defaultRate: 0.96,
    defaultPitch: -0.2,
    defaultIntensity: 82,
    defaultEmotion: 'Suspense',
    defaultEnergy: 75,
    defaultDramatic: 85,
    defaultSuspense: 96,
    pauseSentenceMs: 380,
    pauseParagraphMs: 720,
    emphasisLevel: 'strong',
    actingDirections: 'Tightening coil, increasing vocal pitch slightly across successive sentences, building toward critical rupture.',
    stylePrompt: 'Ratchet up psychological suspense with every passing second like a ticking bomb.'
  },
  {
    id: 'final_reveal',
    number: 57,
    name: 'FINAL REVEAL',
    category: 'Climax & Twist',
    description: 'Ultimate narrative resolution, philosophical synthesis, grand revelation, and definitive clarity.',
    defaultRate: 0.88,
    defaultPitch: -1.5,
    defaultIntensity: 92,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 80,
    defaultDramatic: 95,
    defaultSuspense: 85,
    pauseSentenceMs: 650,
    pauseParagraphMs: 1250,
    emphasisLevel: 'strong',
    actingDirections: 'Solemn finality, laying the ultimate card face up on the table, transcendent narrative resolution.',
    stylePrompt: 'Deliver the final philosophical revelation that ties every thread of the entire film together.'
  },
  {
    id: 'ending',
    number: 58,
    name: 'ENDING',
    category: 'Cinematic & Trailer',
    description: 'Poetic closure, echoing resonance, sunset contemplation, lingering wisdom, and peaceful fade-out.',
    defaultRate: 0.90,
    defaultPitch: -0.8,
    defaultIntensity: 65,
    defaultEmotion: 'Dramatic',
    defaultEnergy: 45,
    defaultDramatic: 80,
    defaultSuspense: 20,
    pauseSentenceMs: 600,
    pauseParagraphMs: 1200,
    emphasisLevel: 'subtle',
    actingDirections: 'Warm sunset contemplation, soothing terminal cadence, gentle fade to credits, poetic philosophical resonance.',
    stylePrompt: 'Speak like the closing monologue of a masterpiece film as the screen gently fades to black.'
  },
  {
    id: 'dark_humor',
    number: 59,
    name: 'DARK HUMOR',
    category: 'Character & Narrative',
    description: 'Macabre amusement, morbid cheer, smiling at catastrophe, and delightfully wicked observations.',
    defaultRate: 1.02,
    defaultPitch: 0.2,
    defaultIntensity: 70,
    defaultEmotion: 'Humorous',
    defaultEnergy: 70,
    defaultDramatic: 60,
    defaultSuspense: 55,
    pauseSentenceMs: 380,
    pauseParagraphMs: 720,
    emphasisLevel: 'sharp',
    actingDirections: 'Playful amusement at bleak realities, eyebrow-raised irony, unapologetic gallows charm.',
    stylePrompt: 'Deliver with delicious gallows humor and sardonic fascination with tragic absurdity.'
  },
  {
    id: 'mature_18',
    number: 60,
    name: 'MATURE / 18+ DELIVERY',
    category: 'Mature & Adult',
    description: 'Mature adult narration style, confident, serious, direct, natural adult conversational delivery, stronger emotional intensity.',
    defaultRate: 0.94,
    defaultPitch: -1.2,
    defaultIntensity: 85,
    defaultEmotion: 'Serious',
    defaultEnergy: 75,
    defaultDramatic: 88,
    defaultSuspense: 75,
    pauseSentenceMs: 460,
    pauseParagraphMs: 880,
    emphasisLevel: 'sharp',
    actingDirections: 'Mature adult narration style, confident, serious, direct, natural adult conversational delivery, stronger emotional intensity where appropriate. Controls DELIVERY ONLY. Does not generate explicit sexual content.',
    stylePrompt: 'Deliver with raw, mature adult gravitas, unflinching honesty, uncompromising realism, and high dramatic intensity.'
  }
];

export function getVoiceActingModeById(id: string): VoiceActingMode {
  const normalized = id.toLowerCase().replace(/[\s\-_]+/g, '_');
  const found = VOICE_ACTING_MODES.find(m => 
    m.id === normalized || 
    m.id === id || 
    m.name.toLowerCase() === id.toLowerCase() ||
    m.name.toLowerCase().replace(/[\s\-_]+/g, '_') === normalized
  );
  return found || VOICE_ACTING_MODES[1]; // default to CINEMATIC
}

export function getAllVoiceActingModes(): VoiceActingMode[] {
  return VOICE_ACTING_MODES;
}

/**
 * Story Engine / AI Recommendation Engine:
 * Recommends optimal Voice Acting Mode and Intensity for a given scene or script section
 */
export function getRecommendedModeForScene(
  sceneType?: string,
  mood?: string,
  hasTwist?: boolean,
  genre?: string
): { modeId: string; intensity: number; reason: string } {
  const combined = `${sceneType || ''} ${mood || ''} ${genre || ''}`.toLowerCase();

  if (hasTwist || combined.includes('twist') || combined.includes('reveal')) {
    return {
      modeId: 'twist_reveal',
      intensity: 88,
      reason: 'AI Recommended: Scene contains pivotal narrative twist point (Stage 9: Reality Inversion).'
    };
  }

  if (combined.includes('action') || combined.includes('chase') || combined.includes('fight') || combined.includes('combat')) {
    return {
      modeId: 'action',
      intensity: 82,
      reason: 'AI Recommended: High-kinetic action sequence requires adrenaline pacing and punchy emphasis.'
    };
  }

  if (combined.includes('mystery') || combined.includes('investigat') || combined.includes('clue') || combined.includes('noir')) {
    return {
      modeId: 'mystery',
      intensity: 68,
      reason: 'AI Recommended: Forensic deduction scene benefits from hushed tension and deliberate clue pauses.'
    };
  }

  if (combined.includes('climax') || combined.includes('final battle') || combined.includes('resolution')) {
    return {
      modeId: 'climax',
      intensity: 95,
      reason: 'AI Recommended: Story culmination demands maximum dramatic intensity and thunderous pauses.'
    };
  }

  if (combined.includes('emotional') || combined.includes('grief') || combined.includes('loss') || combined.includes('love')) {
    return {
      modeId: 'emotional',
      intensity: 72,
      reason: 'AI Recommended: Character tragedy calls for slower empathetic phrasing and emotional weight.'
    };
  }

  if (combined.includes('horror') || combined.includes('terr') || combined.includes('fear') || combined.includes('creepy')) {
    return {
      modeId: 'horror',
      intensity: 85,
      reason: 'AI Recommended: Supernatural or psychological dread requires eerie, restrained pauses.'
    };
  }

  if (combined.includes('news') || combined.includes('breaking') || combined.includes('report')) {
    return {
      modeId: 'breaking_news',
      intensity: 75,
      reason: 'AI Recommended: Live investigative broadcast tempo.'
    };
  }

  if (combined.includes('documentary') || combined.includes('history') || combined.includes('fact')) {
    return {
      modeId: 'documentary',
      intensity: 60,
      reason: 'AI Recommended: Factual historical or analytical breakdown.'
    };
  }

  // Default Cinematic
  return {
    modeId: 'cinematic',
    intensity: 75,
    reason: 'AI Recommended: Master cinematic narrative baseline with controlled dramatic cadence.'
  };
}
